### ISSUE TITLE
registerFamily.dart line 88 pt.update: method not defined

### ISSUE THREAD

**Issue by arfeenmushtaq** [Dokotela/flutter_fhir#1]
Hi, just downloaded your app, but seems like there is an issue with the app
in file registerFamily.dart line 88 pt.update
seems like there is no procedure defined as update for the patient class 
can I use the save function here
![hris_issue01](https://user-images.githubusercontent.com/16346106/86910143-10732900-c0ce-11ea-9743-bada749a3f69.PNG)

**Comment by arfeenmushtaq** [comment]
the application works when changed update to save

**Comment by Dokotela** [comment]
Hey,

Sorry for that, I'm not really maintaining this project anymore. It was my first flutter app, and a lot of it I was just trying to understand how all of it worked. The FHIR resources are all more built out and updated (along with other versions) in my [fhir repo](https://github.com/Dokotela/fhir). Also this app uses [SQFLite](https://pub.dev/packages/sqflite) as the embedded db. I've played around with SQFLite, [moor](https://pub.dev/packages/moor), [hive](https://pub.dev/packages/hive), and eventually settled on [sembast_sqflite](https://pub.dev/packages/sembast_sqflite), after I [spoke with the author](https://github.com/tekartik/sembast.dart/issues/183).

It's in a project in a private repo (and I'm still testing it), but I'm attaching the two files I'm using for it [fhir.embedded.database.tar.gz](https://github.com/Dokotela/flutter_fhir/files/4890768/fhir.embedded.database.tar.gz). As I said, still a work in progress, but I think it's a better way to go than writing all of the sql code myself (which is what I did in this app). It's based mostly on the [Sembast tutorial](https://resocoder.com/2019/04/06/flutter-nosql-database-sembast-tutorial-w-bloc/) from [resocoder](https://resocoder.com/).
